name: Trigger Build on Jitpack

on:
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDK_NAME: "Compose-BeforeAfter"
      USERNAME: "SmartToolFactory"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set BASE_URL Variable
        run: echo "BASE_URL=https://jitpack.io/api/builds/com.github.${USERNAME}/${SDK_NAME}" >> $GITHUB_ENV

      - name: Trigger Jitpack Build for Tagged Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl "${BASE_URL}/${github.ref_name}"

      - name: Trigger Jitpack Build for Master-SNAPSHOT
        if: github.ref == 'refs/heads/master'
        run: |
          curl "${BASE_URL}/master-SNAPSHOT"
